# Generated by Django 5.2 on 2025-05-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount', models.CharField(max_length=20)),
                ('offer_expiry', models.DateField()),
                ('offer_status', models.CharField(choices=[('OPEN', 'Open'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('CONTINGENT', 'Contingent')], default='OPEN')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('BANK_ACCOUNT', 'Bank Account'), ('MORTGAGE', 'Mortgage')])),
                ('national_id', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5)),
                ('cardholder_name', models.CharField(max_length=200)),
                ('credit_card_number', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=10)),
                ('cvc', models.CharField(max_length=5)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('mortgage_provider', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('property_type', models.CharField(max_length=100)),
                ('listing_date', models.DateField()),
                ('listing_price', models.CharField(max_length=15)),
                ('number_of_bedrooms', models.CharField(max_length=2)),
                ('number_of_bathrooms', models.CharField(max_length=2)),
                ('square_meters', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_description', models.TextField()),
            ],
        ),
    ]
