# Generated by Django 5.2 on 2025-05-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('property_type', models.CharField(max_length=100)),
                ('listing_price', models.CharField(max_length=15)),
                ('number_of_bedrooms', models.CharField(max_length=2)),
                ('number_of_bathrooms', models.CharField(max_length=2)),
                ('square_meters', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount', models.CharField(max_length=20)),
                ('propertyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estates.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('propertyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estates.property')),
            ],
        ),
    ]
