# Generated by Django 5.2 on 2025-05-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
