# Generated by Django 5.2 on 2025-05-06 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estates', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.buyer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='real_estates.offer'),
        ),
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
        migrations.AddField(
            model_name='offer',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estates.property'),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estates.property'),
        ),
    ]
