# Generated by Django 5.2 on 2025-05-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='propertyId',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='propertyimages',
            old_name='propertyId',
            new_name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='listing_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
