# Generated by Django 5.2 on 2025-05-08 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cardholder_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mortgage_provider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='street_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('BANK_ACCOUNT', 'Bank Account'), ('MORTGAGE', 'Mortgage')], max_length=16),
        ),
    ]
