# Generated by Django 5.2 on 2025-05-09 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0003_remove_payment_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('CONTINGENT', 'Contingent'), ('PROCESSED', 'Processed')], default='OPEN'),
        ),
    ]
