# Generated by Django 5.2 on 2025-05-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0004_offer_offer_date_alter_offer_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image_url',
            field=models.TextField(),
        ),
    ]
