# Generated by Django 5.2 on 2025-05-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0005_alter_propertyimages_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='square_meters',
            field=models.IntegerField(),
        ),
    ]
