# Generated by Django 5.2 on 2025-05-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0006_alter_property_image_alter_property_listing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SOLD', 'Sold'), ('CONTINGENT', 'Contingent'), ('PROCESSED', 'Processed')], default='OPEN'),
        ),
    ]
