# Generated by Django 5.2 on 2025-05-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0007_alter_property_status'),
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.buyer'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
