# Generated by Django 5.2 on 2025-05-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0008_alter_offer_buyer_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_contingency_message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-offer_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('-listing_date', '-id')},
        ),
    ]
