# Generated by Django 5.2 on 2025-05-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0008_alter_offer_buyer_delete_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('listing_date', 'id')},
        ),
    ]
