# Generated by Django 5.2 on 2025-05-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0009_alter_property_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-offer_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('-listing_date', '-id')},
        ),
    ]
