# Generated by Django 5.2 on 2025-05-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0009_offer_offer_contingency_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_contingency_message',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
