# Generated by Django 5.2 on 2025-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0010_alter_offer_offer_contingency_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='looked_at',
            field=models.IntegerField(default=0),
        ),
    ]
