# Generated by Django 5.2 on 2025-05-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0012_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
