# Generated by Django 5.2 on 2025-05-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estates', '0013_alter_property_image_alter_propertyimages_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image_url',
            field=models.TextField(),
        ),
    ]
