# Generated by Django 5.2 on 2025-05-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Kalli Bjarni', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(default='https://th.bing.com/th/id/OIP.gNTpWUJsGMdT2QV69ASUtAAAAA?rs=1&pid=ImgDetMain'),
            preserve_default=False,
        ),
    ]
