# Generated by Django 5.2 on 2025-05-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_seller_logo_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='price',
        ),
        migrations.AddField(
            model_name='filter',
            name='max_price',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='min_price',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
