# Generated by Django 5.2 on 2025-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_filter_price_filter_max_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='min_price',
        ),
        migrations.AddField(
            model_name='filter',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
