# Generated by Django 5.2 on 2025-05-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_filter_max_price_remove_filter_min_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ('-id', '-monitor')},
        ),
    ]
